server:
  port: 8086


spring:
  profiles:
    active: test

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  servlet:
    #是否支持 multipart 上传文件
    multipart:
      #支持的最大文件
      enabled: true
      #支持的最大文件
      max-file-size: 200MB
      #文件请求最大限制
      max-request-size: 200MB

  #thymeleaf  false关闭缓存 生产可配置true
  thymeleaf:
    cache: false

    # freemarker:
    #allow-request-override: false
    # cache: false
    #check-template-location: true
    # charset: UTF-8
    #content-type: text/html; charset=utf-8
    # expose-request-attributes: false
    #expose-session-attributes: false
    #expose-spring-macro-helpers: false
    # suffix: .ftl
    #template-loader-path: classpath:com.xakj.ant.InsuranceSide.service.impl.template

  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379



logging:
  level:
    main.blog.mapper: trace


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xakj.platform.platform.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

neo:
  title: xxx
  description: xxx

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 127.0.0.1:22122